---
title: "proposal"
author: "Wurongyan Zhang"
date: "12/4/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Proposal: Prevalence trend and Determinants of Suicide Rates
Yingxi Ji (yj2579) 
Yeqing Ji (yj2580)  
Wurongyan Zhang (wz2507)
Yiling Yang  (yy3018) 

 
According to the World Health Organization, every year, about 800,000 people die due to suicide. In this project, we are wondering the trend of suicide rate across years. The anticipated dataset is a combined dataset from summary datasets made by United Nations Development Program, World Bank, Kaggle, and World Health Organization, which can be access at https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016. The dataset contains suicide rate and relative dataset from 1985 to 2016. In particular, we are interested in:
1. What’s the general trend of suicide rate globally across the time.
2. Is there any gender difference in suicide rate across the time.
3. Is there any age difference in suicide rate across the time.
4. The relationship between the development of a country (GDP) and suicide rate across time.

Planned analyses begin with data cleaning and EDA. This step includes visualization, possibly interactive, by using graphs such as bar graphs, correlation matrix and heat map. Proportional hypothesis test and regression are followed. An interactive map might be considered. The intended outputs include: 1) A web page containing report and interactive tools, and 2) A video demonstration of webpage and report. Expected coding challenges are mostly about how to use website to show the trend across many factors such as time or region. 
 
# The planned timeline
Nov 20: Finish EDA and interested questions 
Dec 1: Build website
Dec 4: Make video
